version: '3.8'

networks:
  yiguard-network:
    external: true

services:
  yiguard-mysql:
    image: mysql:8.0
    container_name: yiguard-mysql
    restart: always
    networks:
      - yiguard-network
    ports:
      - "33306:3306"
    volumes:
      - /data/yiguard-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: yiguard260604
      MYSQL_DATABASE: yifa_silver_guard

  yiguard-redis:
    image: redis:latest
    container_name: yiguard-redis
    restart: always
    networks:
      - yiguard-network
    ports:
      - "6390:6379"

  yiguard-app:
    image: openjdk:17
    container_name: yiguard-app
    restart: always
    networks:
      - yiguard-network
    ports:
      - "8083:8081"
    volumes:
      - ./app.jar:/app.jar
    command: java -jar /app.jar --server.address=0.0.0.0 --server.port=8081
    depends_on:
      - yiguard-mysql
      - yiguard-redis